name: rountiner
description: "Flutter application for managing daily routines and habits."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Navigation
  auto_route: ^9.3.0
  connectivity_plus: ^6.1.3

  # State management    
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

  # Firebase
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  provider: ^6.1.2
  google_sign_in: ^6.2.2

  # Annotations
  json_annotation: ^4.9.0

  # File handling
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.1

  # Utils
  flutter_svg: ^2.0.17
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  intl_utils: ^2.8.9
  firebase_messaging: ^15.2.2
  firebase_analytics: ^11.4.2
  flutter_local_notifications: ^18.0.1
  http: ^1.3.0
  dartz: ^0.10.1
  flutter_facebook_auth: ^6.0.4
  facebook_auth_desktop: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  integration_test:
    sdk: flutter

  build_runner: ^2.4.14
  auto_route_generator: ^9.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3

flutter:  
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - .env
    
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal-Medium.otf
          weight: 500 # Medium
        - asset: assets/fonts/AirbnbCereal-Normal.otf
          weight: 400 # Book (обычный)
        - asset: assets/fonts/AirbnbCereal-Bold.otf
          weight: 700 # Bold (если есть)

    
flutter_intl:
  enabled: true
